@startuml
hide circle
hide empty members

entity users {
	user_id BIGINT PK
	--
	email VARCHAR(320)
	first_name VARCHAR(255)
	last_name VARCHAR(255)
	password_hash VARBINARY(255)
	middle_name VARCHAR(255)
}

entity users_sessions {
    session_hash BINARY(32) PK
	user_id BIGINT FK
	--
	expires_at DATETIME(6)
}

entity teachers {
    teacher_id BIGINT PK
    --
    first_name VARCHAR(255)
	last_name VARCHAR(255)
	middle_name VARCHAR(255)
}

entity schools {
    school_id BIGINT PK
    --
    name VARCHAR(255)
}

entity departments {
    department_id BIGINT PK
    school_id BIGINT FK
    --
    name VARCHAR(255)
}

entity academic_terms {
    academic_term_id BIGINT PK
    name VARCHAR(255)
}

entity semesters {
	semester_id BIGINT PK
	academic_term_id BIGINT FK
	--
	academic_year UNSIGNED INT
	max_units UNSIGNED INT
}

entity programs {
    program_id BIGINT PK
    department_id BIGINT FK
    --
    name VARCHAR(255)
}

entity courses {
    course_id BIGINT PK
    --
    course_code VARCHAR(255)
    name VARCHAR(255)
	units UNSIGNED INT
}

entity prerequisites {
    course_id BIGINT FK
    prerequisite_course_id BIGINT FK
}

entity corequisites {
    course_id BIGINT FK
    corequisite_course_id BIGINT FK
}

entity prospectuses {
    prospectus_id BIGINT PK
    program_id BIGINT FK
    --
	academic_year UNSIGNED INT
}

entity prospectuses_courses {
    prospectus_course_id BIGINT PK
    prospectus_id BIGINT FK
    course_id BIGINT FK
    academic_term_id BIGINT FK
    min_year_standing UNSIGNED INT
}

entity sections {
    section_id BIGINT PK
    course_id BIGINT FK
    semester_id BIGINT FK
    teacher_id BIGINT FK
    reserved_department_id BIGINT FK
    --
	name VARCHAR(255)
    current_students UNSIGNED INT
    max_students UNSIGNED INT
    status ENUM('BLOCK', 'REGULAR', 'HONORARIUM', 'PETITION', 'DISSOLVED')
}

entity timetables {
    timetable_id BIGINT PK
    section_id BIGINT FK
    --
    day ENUM('MON','TUE','WED','THU','FRI','SAT','SUN')
    start_time TIME(0)
    end_time TIME(0)
}

entity calendars {
	calendar_id BIGINT PK
	user_id BIGINT FK
	--
	name VARCHAR(255)
}

entity calendars_semesters {
    calendar_semester_id BIGINT PK
    calendar_id BIGINT FK
    semester_id BIGINT FK
    program_id BIGINT FK
}

entity calendars_semesters_sections {
    calendar_semester_id BIGINT FK
    section_id BIGINT FK
}

entity completed_courses {
    user_id BIGINT FK
    prospectus_course_id BIGINT FK
    semester_id BIGINT FK
    --
    from_admin BOOLEAN
}

entity groups {
    group_id BIGINT PK
    --
    name VARCHAR(255)
}

entity groups_courses {
    group_id BIGINT FK
    course_id BIGINT FK
}

entity prospectuses_groups {
    prospectus_group_id BIGINT PK
    prospectus_id BIGINT FK
    group_id BIGINT FK
    academic_term_id BIGINT FK
    min_year_standing UNSIGNED INT
}

users ||--o{ users_sessions
users ||--o{ calendars
schools ||--|{ departments
departments ||--|{ programs
departments ||--|{ sections
programs ||--|{ prospectuses
prospectuses ||--|{ prospectuses_courses
courses ||--|{ prospectuses_courses
courses ||--|{ sections
courses ||--|{ prerequisites
courses ||--|{ corequisites
semesters ||--|{ sections
academic_terms ||--|{ semesters
academic_terms ||--|{ prospectuses_courses
teachers ||--|{ sections
calendars ||--o{ calendars_semesters
semesters ||--o{ calendars_semesters
programs ||--o{ calendars_semesters
calendars_semesters ||--o{ calendars_semesters_sections
sections ||--o{ calendars_semesters_sections
sections ||--|{ timetables
users ||--o{ completed_courses
prospectuses_courses ||--o{ completed_courses
semesters ||--o{ completed_courses
groups ||--|{ groups_courses
courses ||--|{ groups_courses
prospectuses ||--|{ prospectuses_groups
groups ||--|{ prospectuses_groups
academic_terms ||--|{ prospectuses_groups

@enduml
